/home/ubuntu/miniconda3/envs/qml/lib/python3.10/site-packages/sklearn/base.py:380: InconsistentVersionWarning: Trying to unpickle estimator MinMaxScaler from version 1.5.1 when using version 1.6.1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
capi_return is NULL
Call-back cb_calcfc_in__cobyla__user__routines failed.
(19, 64) (40, 64)
None
Parameters from scratch
[-2.90318345  2.23743464 -2.12427964 -0.11653103  0.55388708 -2.77010897
  3.06858498  2.18960145  1.18551998 -1.06648308  0.6027151   1.14432445
  1.31029899 -1.8735468   0.7296508  -2.90318345  2.23743464 -2.12427964
 -0.11653103  0.55388708 -2.77010897  3.06858498  2.18960145  1.18551998
 -1.06648308  0.6027151   1.14432445  1.31029899 -1.8735468   0.7296508
 -2.90318345  2.23743464 -2.12427964 -0.11653103  0.55388708 -2.77010897
  3.06858498  2.18960145  1.18551998 -1.06648308  0.6027151   1.14432445
  1.31029899 -1.8735468   0.7296508  -2.90318345  2.23743464 -2.12427964
 -0.11653103  0.55388708 -2.77010897  3.06858498  2.18960145  1.18551998
 -1.06648308  0.6027151   1.14432445  1.31029899 -1.8735468   0.7296508
 -2.90318345  2.23743464 -2.12427964 -0.11653103  0.55388708 -2.77010897
  3.06858498  2.18960145  1.18551998 -1.06648308  0.6027151   1.14432445
  1.31029899 -1.8735468   0.7296508 ]
[SparsePauliOp(['IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIZIIIIIIIIIIIIIIIIIIIIIIIIII'],
              coeffs=[1.+0.j])]
<IBMBackend('ibm_quebec')>
Mappings: 0it [00:00, ?it/s]
Submitted to device in 79.7686 s
Predicted in 7780.3447 s
return (64, 19)
Iters. done: 1 Current cost: 0.13091599787023292 Accuracy: -0.3725136849090598 Time: 7860.52737160027
Mappings: 0it [00:00, ?it/s]
Submitted to device in 78.0456 s
Predicted in 8098.6488 s
return (64, 19)
Iters. done: 2 Current cost: 0.1300027575118835 Accuracy: -0.3629393402159973 Time: 8177.156098883599
Mappings: 0it [00:00, ?it/s]
Submitted to device in 102.8091 s
Predicted in 5906.3967 s
return (64, 19)
Iters. done: 3 Current cost: 0.13214531200233878 Accuracy: -0.38540172377990745 Time: 6009.59025271982
Mappings: 0it [00:00, ?it/s]
Submitted to device in 85.5272 s
Predicted in 6291.7758 s
return (64, 19)
Iters. done: 4 Current cost: 0.1302353658398049 Accuracy: -0.3653779888035624 Time: 6377.705461032689
Mappings: 0it [00:00, ?it/s]
Submitted to device in 75.4135 s
Predicted in 5608.1640 s
return (64, 19)
Iters. done: 5 Current cost: 0.12944913849704978 Accuracy: -0.3571352392165279 Time: 5684.023866679519
Mappings: 0it [00:00, ?it/s]
Submitted to device in 59.5785 s
Predicted in 11737.7958 s
return (64, 19)
Iters. done: 6 Current cost: 0.12920123248924384 Accuracy: -0.35453621087911946 Time: 11798.304376859218
Mappings: 0it [00:00, ?it/s]
Submitted to device in 64.6608 s
Predicted in 5513.7863 s
return (64, 19)
Iters. done: 7 Current cost: 0.1300230596611871 Accuracy: -0.3631521864548495 Time: 5579.322858482599
Mappings: 0it [00:00, ?it/s]
Submitted to device in 67.0274 s
Predicted in 5528.8309 s
return (64, 19)
Iters. done: 8 Current cost: 0.1304461018541301 Accuracy: -0.3675873296654122 Time: 5596.299581889063
Mappings: 0it [00:00, ?it/s]
Submitted to device in 58.2399 s
Predicted in 5513.8810 s
return (64, 19)
Iters. done: 9 Current cost: 0.13007738764995994 Accuracy: -0.3637217570900457 Time: 5572.537217542529
Mappings: 0it [00:00, ?it/s]
Submitted to device in 60.7913 s
Predicted in 5562.1381 s
return (64, 19)
Iters. done: 10 Current cost: 0.13025813698896918 Accuracy: -0.36561671985521027 Time: 5623.320928491652
Mappings: 0it [00:00, ?it/s]
Submitted to device in 67.1262 s
Predicted in 5415.7126 s
return (64, 19)
Iters. done: 11 Current cost: 0.12997536431067266 Accuracy: -0.3626521519109238 Time: 5483.217722505331
Mappings: 0it [00:00, ?it/s]
Submitted to device in 63.4074 s
Predicted in 13060.4050 s
return (64, 19)
Iters. done: 12 Current cost: 0.12952433240296346 Accuracy: -0.35792356659108293 Time: 13124.19107202068
Mappings: 0it [00:00, ?it/s]
Submitted to device in 56.0328 s
Predicted in 5609.8449 s
return (64, 19)
Iters. done: 13 Current cost: 0.12857865592285594 Accuracy: -0.34800916398514037 Time: 5666.838673416525
Mappings: 0it [00:00, ?it/s]
Submitted to device in 64.0133 s
Predicted in 6300.7034 s
return (64, 19)
Iters. done: 14 Current cost: 0.13082834526143622 Accuracy: -0.3715947414105676 Time: 6365.158763982356
Mappings: 0it [00:00, ?it/s]
Submitted to device in 59.9731 s
urllib3.exceptions.ResponseError: too many 503 error responses

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/qml/lib/python3.10/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
  File "/home/ubuntu/miniconda3/envs/qml/lib/python3.10/site-packages/urllib3/connectionpool.py", line 942, in urlopen
    return self.urlopen(
  File "/home/ubuntu/miniconda3/envs/qml/lib/python3.10/site-packages/urllib3/connectionpool.py", line 942, in urlopen
    return self.urlopen(
  File "/home/ubuntu/miniconda3/envs/qml/lib/python3.10/site-packages/urllib3/connectionpool.py", line 942, in urlopen
    return self.urlopen(
  [Previous line repeated 2 more times]
  File "/home/ubuntu/miniconda3/envs/qml/lib/python3.10/site-packages/urllib3/connectionpool.py", line 932, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
  File "/home/ubuntu/miniconda3/envs/qml/lib/python3.10/site-packages/qiskit_ibm_runtime/api/session.py", line 126, in increment
    return super().increment(
  File "/home/ubuntu/miniconda3/envs/qml/lib/python3.10/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.quantum.ibm.com', port=443): Max retries exceeded with url: /runtime/jobs/d08j1pyd8drg0081h10g?exclude_params=true (Caused by ResponseError('too many 503 error responses'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/qml/lib/python3.10/site-packages/qiskit_ibm_runtime/api/session.py", line 328, in request
    response = super().request(method, final_url, headers=headers, **kwargs)
  File "/home/ubuntu/miniconda3/envs/qml/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ubuntu/miniconda3/envs/qml/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/ubuntu/miniconda3/envs/qml/lib/python3.10/site-packages/requests/adapters.py", line 691, in send
    raise RetryError(e, request=request)
requests.exceptions.RetryError: HTTPSConnectionPool(host='api.quantum.ibm.com', port=443): Max retries exceeded with url: /runtime/jobs/d08j1pyd8drg0081h10g?exclude_params=true (Caused by ResponseError('too many 503 error responses'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/real/ol3_rl2/real.py", line 216, in <module>
    model.fit(X_train,y_train)
  File "/home/ubuntu/real/ol3_rl2/QiskitRegressor.py", line 411, in fit
    res = minimize(self._cost_func,
  File "/home/ubuntu/miniconda3/envs/qml/lib/python3.10/site-packages/scipy/optimize/_minimize.py", line 744, in minimize
    res = _minimize_cobyla(fun, x0, args, constraints, callback=callback,
  File "/home/ubuntu/miniconda3/envs/qml/lib/python3.10/site-packages/scipy/optimize/_cobyla_py.py", line 35, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/qml/lib/python3.10/site-packages/scipy/optimize/_cobyla_py.py", line 293, in _minimize_cobyla
    xopt, info = cobyla.minimize(calcfc, m=m, x=np.copy(x0), rhobeg=rhobeg,
  File "/home/ubuntu/miniconda3/envs/qml/lib/python3.10/site-packages/scipy/optimize/_cobyla_py.py", line 281, in calcfc
    f = sf.fun(x)
  File "/home/ubuntu/miniconda3/envs/qml/lib/python3.10/site-packages/scipy/optimize/_differentiable_functions.py", line 326, in fun
    self._update_fun()
  File "/home/ubuntu/miniconda3/envs/qml/lib/python3.10/site-packages/scipy/optimize/_differentiable_functions.py", line 295, in _update_fun
    fx = self._wrapped_fun(self.x)
  File "/home/ubuntu/miniconda3/envs/qml/lib/python3.10/site-packages/scipy/optimize/_differentiable_functions.py", line 21, in wrapped
    fx = fun(np.copy(x), *args)
  File "/home/ubuntu/real/ol3_rl2/QiskitRegressor.py", line 361, in _cost_func
    y_pred = self.predict(X,parameters,iters=self.cost_history_dict["iters"])
  File "/home/ubuntu/real/ol3_rl2/QiskitRegressor.py", line 320, in predict
    y_pred = self.get_results(filename)
  File "/home/ubuntu/real/ol3_rl2/QiskitRegressor.py", line 207, in get_results
    pred = np.hstack([np.vstack([r.data.evs for r in self.service.job(jid.strip()).result()]) for jid in f.readlines()])
  File "/home/ubuntu/real/ol3_rl2/QiskitRegressor.py", line 207, in <listcomp>
    pred = np.hstack([np.vstack([r.data.evs for r in self.service.job(jid.strip()).result()]) for jid in f.readlines()])
  File "/home/ubuntu/miniconda3/envs/qml/lib/python3.10/site-packages/qiskit_ibm_runtime/runtime_job_v2.py", line 133, in result
    self.wait_for_final_state(timeout=timeout)
  File "/home/ubuntu/miniconda3/envs/qml/lib/python3.10/site-packages/qiskit_ibm_runtime/runtime_job_v2.py", line 253, in wait_for_final_state
    status = self.status()
  File "/home/ubuntu/miniconda3/envs/qml/lib/python3.10/site-packages/qiskit_ibm_runtime/runtime_job_v2.py", line 170, in status
    self._set_status_and_error_message()
  File "/home/ubuntu/miniconda3/envs/qml/lib/python3.10/site-packages/qiskit_ibm_runtime/base_runtime_job.py", line 207, in _set_status_and_error_message
    response = self._api_client.job_get(job_id=self.job_id())
  File "/home/ubuntu/miniconda3/envs/qml/lib/python3.10/site-packages/qiskit_ibm_runtime/api/clients/runtime.py", line 115, in job_get
    response = self._api.program_job(job_id).get(exclude_params=exclude_params)
  File "/home/ubuntu/miniconda3/envs/qml/lib/python3.10/site-packages/qiskit_ibm_runtime/api/rest/program_job.py", line 59, in get
    return self.session.get(self.get_url("self"), params=payload).json(cls=RuntimeDecoder)
  File "/home/ubuntu/miniconda3/envs/qml/lib/python3.10/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/home/ubuntu/miniconda3/envs/qml/lib/python3.10/site-packages/qiskit_ibm_runtime/api/session.py", line 351, in request
    raise RequestsApiError(message, status_code) from ex
qiskit_ibm_runtime.api.exceptions.RequestsApiError: "HTTPSConnectionPool(host='api.quantum.ibm.com', port=443): Max retries exceeded with url: /runtime/jobs/d08j1pyd8drg0081h10g?exclude_params=true (Caused by ResponseError('too many 503 error responses'))"
